#
# Enable these APIs before deploying config:
# - gcloud services enable \
# deploymentmanager.googleapis.com \
# cloudresourcemanager.googleapis.com \
# iam.googleapis.com \
# servicemanagement.googleapis.com
#
# Give Google APIs Service Agent Service Account the primative project Owner Role (default is primative Editor) 
# Necessary to update project IAM policy
#
# roles/storage.admin role to the service account DM uses Google APIs Service Agent Service Account
#
imports:
- path: apis.jinja
- path: service_account.jinja
- path: storage.jinja
- path: cloudsql.jinja

resources:

- name: enable-apis
  type: apis.jinja
  properties:
    apis:
    - cloudresourcemanager.googleapis.com
    - servicemanagement.googleapis.com
    - deploymentmanager.googleapis.com
    - iam.googleapis.com
    - run.googleapis.com
    - compute.googleapis.com
    - sql-component.googleapis.com
    - sqladmin.googleapis.com
    - cloudbuild.googleapis.com
    - cloudkms.googleapis.com
    - secretmanager.googleapis.com

- name: service-account
  type: iam.v1.serviceAccount
  properties:
    accountId: feedme-api
    displayName: api service account

#  serviceAccount:{{ properties["saAccountId"] }}@{{ env["project"] }}.iam.gserviceaccount.com
- name: policy-bindings
  type: policy_bindings.jinja
  metadata:
    dependsOn:
    - service-account
    - serviceAccountIAMBinding-cloudresourcemanager.googleapis.com
  properties:
    saAccountId: feedme-api
    roles:
    - cloudsql.client
    - run.admin

- name: cloud-storage-bucket
  type: storage.jinja
  properties:
    region: us-central1
    storageClass: REGIONAL

- name: cloudsql
  type: cloudsql.jinja
  properties:
    region: us-central1
    databaseVersion: POSTGRES_11
    settings:
      tier: db-f1-micro
      backupConfiguration:
        enabled: false
      locationPreference:
        zone: us-central1-a
    database:
      name: api
      users:
      - name: user
        password: password