# Generated by Django 3.0.4 on 2020-05-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='datafile',
            field=models.FileField(upload_to='photos'),
        ),
    ]
