# Generated by Django 3.0.4 on 2020-05-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200515_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='datafile',
            new_name='image_data',
        ),
    ]
