# Generated by Django 3.0.4 on 2020-05-15 15:14

from django.db import migrations, models
import django.db.models.deletion
import project.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200515_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default='Test', upload_to=project.helpers.RandomFileName('images')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
