# Generated by Django 3.0.4 on 2020-05-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200515_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='feed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FeedItem'),
        ),
        migrations.CreateModel(
            name='FeedItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
                ('feedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedItem')),
            ],
        ),
    ]
