# Generated by Django 3.0.4 on 2020-05-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200515_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='feed_item',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
