# Generated by Django 3.0.4 on 2020-05-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200515_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditemcomment',
            name='feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.FeedItem'),
        ),
    ]
