# Generated by Django 3.0.4 on 2020-05-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200515_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='feed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_item', to='api.FeedItem'),
        ),
    ]
